version: '3.8'

services:
  bot1:
    build: .
    container_name: trayb-recorder-bot1
    command: npm run bot1
    environment:
      - BOT1_TOKEN=${BOT1_TOKEN}
      - BOT1_AUTHORIZED_USERS=${BOT1_AUTHORIZED_USERS}
      - BOT1_UPLOAD_CHANNEL_ID=${BOT1_UPLOAD_CHANNEL_ID}
      - WEB_URL=${WEB_URL:-https://rec.trayb.az}
      - NODE_ENV=production
    volumes:
      - ./output:/app/output
      - ./data:/app/data
      - ./recordings:/app/recordings
    restart: unless-stopped
    networks:
      - recorder-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bot2:
    build: .
    container_name: trayb-recorder-bot2
    command: npm run bot2
    environment:
      - BOT2_TOKEN=${BOT2_TOKEN}
      - BOT2_AUTHORIZED_USERS=${BOT2_AUTHORIZED_USERS}
      - BOT2_UPLOAD_CHANNEL_ID=${BOT2_UPLOAD_CHANNEL_ID}
      - WEB_URL=${WEB_URL:-https://rec.trayb.az}
      - NODE_ENV=production
    volumes:
      - ./output:/app/output
      - ./data:/app/data
      - ./recordings:/app/recordings
    restart: unless-stopped
    networks:
      - recorder-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: .
    container_name: trayb-recorder-web
    command: npm run web
    ports:
      - "8080:8080"
    environment:
      - WEB_PORT=8080
      - WEB_URL=${WEB_URL:-https://rec.trayb.az}
      - NODE_ENV=production
    volumes:
      - ./output:/app/output
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - recorder-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/matches"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  recorder-network:
    driver: bridge

volumes:
  output:
  data:
  recordings:
